### ISSUE TITLE
[Developer Essentials] 10.3 Iteration Plan

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/developer-essentials#10]
# 10.3 Iteration Plan

This plan captures our work on the Carbon Developer Essentials project for **May**. This work will result in a multi-step developer tutorial for Carbon React.

## Endgame

- **May 27th, 2019**: Code freeze for the endgame
- **May 31st, 2019**: Endgame done

## React Tutorial

Development timeline to have tutorial content and documentation ready by week of 5/20/19 where we'll be doing a dry run with various developers in Austin.

- [x] 4/26 tutorial designed @aagonzales @jeanservaas 
- [x] 4/26 `tutorial-repo` ready #6 @joshblack @jnm2377 
- [x] 4/26 `carbon-website` content strategy #7 @designertyler @connor-leech 
- [x] 5/1 step 1 code and content #1 @aledavila @jnm2377 
- [x] 5/6 step 2 code and content #2 @emyarod @jnm2377 
- [x] 5/9 step 3 code and content #3 @vpicone @dakahn 
- [x] 5/14 step 4 code and content #4 @lovemecomputer @dakahn 
- [x] 5/17 step 5 code and content #5 @alisonjoseph @tw15egan 
- [x] 5/17 overview page with prerequisites #8 @mattrosno

## More Information

More information about the Developer Essentials dates, locations, and format can be found here: https://github.com/carbon-design-system/developer-essentials

## Known Issues

- Nested grid support https://github.com/carbon-design-system/carbon/issues/2792
- React data table borders on hover https://github.com/carbon-design-system/carbon/issues/2723
- UI shell content does not render in IE11 https://github.com/carbon-design-system/carbon/issues/2789
- Hover underline in website anchor links columns https://github.com/carbon-design-system/carbon-website/issues/1656
- Website h5 pseudo-elements covering anchors https://github.com/carbon-design-system/carbon-website/issues/649
- Website special characters in anchor links https://github.com/carbon-design-system/carbon-website/issues/1727
